package com.valhalla.valhalla.config

import com.squareup.moshi.JsonDataException
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import com.valhalla.config.models.AdditionalData
import com.valhalla.config.models.ValhallaConfig
import java.io.File
import java.io.IOException

/**
 * Builds a [ValhallaConfig] from the same defaults iOS starts from.
 *
 * Every function here mirrors an initializer on the Swift `ValhallaConfig` extension, so a
 * config built on one platform matches the config built on the other:
 *
 * | Kotlin | Swift |
 * | --- | --- |
 * | [default] | `ValhallaConfig()` |
 * | [fromJson] | `ValhallaConfig(_:using:)` |
 * | [fromFile] | `ValhallaConfig(fromURL:)` |
 * | [usingTileExtract] | `ValhallaConfig(tileExtractTar:elevationDir:)` |
 * | [usingTilesDir] | `ValhallaConfig(tilesDir:elevationDir:)` |
 * | [usingTileUrl] | `ValhallaConfig(tilesUrl:tilesDir:tilesAreGzFiles:)` |
 *
 * The defaults are read from a bundled `default.json` rather than written out in Kotlin. That
 * file is generated by valhalla's own `scripts/valhalla_build_config` from the pinned submodule
 * — see `scripts/generate_default_config.sh` — and iOS bundles the identical bytes. Reading it
 * is what keeps the two platforms' defaults from drifting apart, and it also sidesteps the
 * defaults baked into the generated model classes, several of which do not match valhalla's.
 *
 * None of this needs an Android [android.content.Context]: the config is a plain object, and it
 * only becomes a file when [ValhallaConfigManager] writes it.
 */
object ValhallaConfigFactory {

    /**
     * The bundled valhalla defaults, as a java resource on the classpath.
     *
     * A java resource rather than an Android asset or a raw resource, so that building a config
     * needs no `Context` — matching iOS, where it is an SPM bundle resource.
     */
    private const val DEFAULT_CONFIG_RESOURCE = "/com/valhalla/valhalla/default.json"

    private val defaultMoshi: Moshi by lazy { Moshi.Builder().add(KotlinJsonAdapterFactory()).build() }

    /**
     * Parsed once. [ValhallaConfig] is an immutable data class, so every caller can share it and
     * build on it with `copy`.
     */
    private val defaultConfig: ValhallaConfig by lazy { readDefault(defaultMoshi) }

    /**
     * The valhalla defaults for the version this library is built against.
     *
     * Use this to adjust a handful of values on top of a working baseline. It points at no tiles,
     * so pass it through one of the `using` functions, or set [com.valhalla.config.models.Mjolnir]
     * paths yourself, before handing it to
     * [com.valhalla.valhalla.Valhalla].
     */
    fun default(): ValhallaConfig = defaultConfig

    /**
     * Parses a complete valhalla config from a JSON string.
     *
     * The JSON must be a functional valhalla config whose tile paths are already correct for this
     * device. [usingTileExtract] and [usingTilesDir] do that part for you.
     *
     * @throws IllegalArgumentException if the JSON is malformed or is not a valhalla config.
     */
    fun fromJson(json: String, moshi: Moshi = defaultMoshi): ValhallaConfig =
        try {
            moshi.adapter(ValhallaConfig::class.java).fromJson(json)
                ?: throw IllegalArgumentException("the valhalla config JSON was the literal null")
        } catch (e: JsonDataException) {
            throw IllegalArgumentException("the valhalla config JSON could not be read", e)
        } catch (e: IOException) {
            throw IllegalArgumentException("the valhalla config JSON was malformed", e)
        }

    /**
     * Parses a complete valhalla config from a file on disk.
     *
     * @throws IllegalArgumentException if the file is malformed or is not a valhalla config.
     * @throws IOException if the file cannot be read.
     */
    fun fromFile(file: File, moshi: Moshi = defaultMoshi): ValhallaConfig =
        fromJson(file.readText(), moshi)

    /**
     * The defaults, pointed at a tile tarball.
     *
     * @param tileExtractTar absolute path of the tiles tar, e.g. from
     *   [com.valhalla.valhalla.files.ValhallaFile.absolutePath].
     * @param elevationDir absolute path of a directory of skadi elevation tiles. Without it every
     *   height from [com.valhalla.valhalla.Valhalla.height] is null.
     */
    fun usingTileExtract(tileExtractTar: String, elevationDir: String? = null): ValhallaConfig {
        val config = default()
        return config
            .copy(mjolnir = config.mjolnir?.copy(tileExtract = tileExtractTar))
            .withElevation(elevationDir)
    }

    /**
     * The defaults, pointed at a directory of loose tiles.
     *
     * A tile directory makes distinct offline regions easier to manage; a tarball is faster.
     *
     * @param tilesDir absolute path of the tiles directory.
     * @param elevationDir absolute path of a directory of skadi elevation tiles.
     */
    fun usingTilesDir(tilesDir: String, elevationDir: String? = null): ValhallaConfig {
        val config = default()
        return config
            .copy(mjolnir = config.mjolnir?.copy(tileDir = tilesDir))
            .withElevation(elevationDir)
    }

    /**
     * The defaults, pointed at a tile server that tiles are downloaded from on demand and cached
     * in [tilesDir].
     *
     * Valhalla fills the `{tilePath}` portion of [tilesUrl] in with the tile it wants.
     *
     * Downloading needs [com.valhalla.valhalla.Valhalla] to have been built with an HTTP client,
     * which it is by default. A config built this way against a build with no client reports
     * every missing tile as a fetch failure.
     *
     * @param tilesUrl the URL pattern tiles are fetched from.
     * @param tilesDir absolute path of the directory downloaded tiles are stored in.
     * @param tilesAreGzFiles whether the server serves gzip-compressed tiles.
     */
    fun usingTileUrl(
        tilesUrl: String,
        tilesDir: String,
        tilesAreGzFiles: Boolean = false
    ): ValhallaConfig {
        val config = default()
        return config.copy(
            mjolnir =
                config.mjolnir?.copy(
                    tileUrl = tilesUrl,
                    tileUrlGz = tilesAreGzFiles,
                    tileDir = tilesDir),
            // The connectivity map is built from the tiles that are present, so it cannot answer
            // for tiles that have not been downloaded yet. Swift's
            // `ValhallaConfig(tilesUrl:tilesDir:tilesAreGzFiles:)` turns it off for the same reason.
            loki = config.loki?.copy(useConnectivity = false))
    }

    /** Returns this config with [elevationDir] set, or unchanged when it is null. */
    private fun ValhallaConfig.withElevation(elevationDir: String?): ValhallaConfig =
        if (elevationDir == null) this
        else
            copy(
                additionalData =
                    (additionalData ?: AdditionalData()).copy(elevation = elevationDir))

    private fun readDefault(moshi: Moshi): ValhallaConfig {
        // The resource ships inside this library's own artifact, so a failure here means the
        // packaging is broken rather than anything a caller did.
        val json =
            ValhallaConfigFactory::class
                .java
                .getResourceAsStream(DEFAULT_CONFIG_RESOURCE)
                ?.use { it.readBytes().decodeToString() }
                ?: throw IllegalStateException(
                    "$DEFAULT_CONFIG_RESOURCE is missing from the valhalla-mobile artifact")

        return fromJson(json, moshi)
    }
}
