name: Build Valhalla Mobile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14

    steps:
    - name: Checkout Valhalla
      uses: actions/checkout@v4

    - name: Build all
      run: ./build.sh