name: Valhalla Mobile iOS

on:
  release:
    types: [created]

jobs:
  publish-release:
    if: github.event.release.draft == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get the actual commit for the tag
        id: get-commit
        run: echo ::set-output name=commit::$(git rev-list -n 1 ${{ github.event.release.tag_name }}-actual)

      - name: Update Tag to Specific Commit
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/git/refs/tags/${{ github.event.release.tag_name }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          sha: ${{ steps.get-commit.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}