name: Test Valhalla Mobile iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  scheme: Valhalla

jobs:
  test:
    runs-on: macos-14
    strategy:
      matrix:
        destination: [
          'platform=iOS Simulator,name=iPhone 14,OS=17.2'
        ]

    steps:
    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Checkout Valhalla
      uses: actions/checkout@v3

    - name: Test on ${{ matrix.destination }}
      run: xcodebuild -scheme ${scheme} test -sdk iphonesimulator -destination '${{ matrix.destination }}' | xcbeautify && exit ${PIPESTATUS[0]}